 CREATE TABLE IF NOT EXISTS `mydb`.`Customer` (   `Customer_id` VARCHAR(5) NOT NULL,   `fname` VARCHAR(15) NOT NULL,   `Lname` VARCHAR(15) NULL,   `gender` VARCHAR(15) NOT NULL,   `dob` DATE NOT NULL,   `email_id` VARCHAR(30) NOT NULL,   PRIMARY KEY (`Customer_id`))   ENGINE = InnoDB; 
 
 CREATE TABLE IF NOT EXISTS `mydb`.`Manufacturer` (   `Manufacturer_id` VARCHAR(5) NOT NULL,   `Manufacturer_Name` VARCHAR(20) NULL,    PRIMARY KEY (`Manufacturer_id`))    ENGINE = InnoDB
 
 CREATE TABLE IF NOT EXISTS `mydb`.`Car_Company` (   `company_id` VARCHAR(5) NOT NULL,   `Company_name` VARCHAR(15) NULL,   `No_of_employees` INT NULL,   `fk_Manufacture_id_company` VARCHAR(5) NOT NULL,   PRIMARY KEY (`company_id`),   INDEX `fk_Car_Company_Manufacture1_idx` (`fk_Manufacture_id_company` ASC),   CONSTRAINT `fk_Manufacturer_id_company`     FOREIGN KEY (`fk_Manufacture_id_company`)     REFERENCES `mydb`.`Manufacturer` (`Manufacturer_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION) ENGINE = InnoDB;   
 
 CREATE TABLE IF NOT EXISTS `mydb`.`Showroom` (   `Showroom_id` VARCHAR(5) NOT NULL,   `Showroom_Name` VARCHAR(20) NULL,   `No_of_employees` INT NULL,   `fk_company_id_showroom` VARCHAR(5) NOT NULL,   PRIMARY KEY (`Showroom_id`),   INDEX `fk_Showroom_Car_Company1_idx` (`fk_company_id_showroom` ASC),   CONSTRAINT `fk_company_id_showroom`     FOREIGN KEY (`fk_company_id_showroom`)     REFERENCES `mydb`.`Car_Company` (`company_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION) 

CREATE TABLE IF NOT EXISTS `mydb`.`address` (   `zip_code` INT NOT NULL,   `street_address` VARCHAR(45) NOT NULL,   `city` VARCHAR(15) NOT NULL,   `state` VARCHAR(15) NOT NULL,   `country` VARCHAR(15) NOT NULL,   `fk_Customer_id_address` VARCHAR(5) NULL,   `fk_Manufacturer_id_address` VARCHAR(5) NULL,   `Showroom_Showroom_id` VARCHAR(5) NULL,   INDEX `fk_address_Customer1_idx` (`fk_Customer_id_address` ASC),   INDEX `fk_address_Manufacturer1_idx` (`fk_Manufacturer_id_address` ASC),   INDEX `fk_address_Showroom1_idx` (`Showroom_Showroom_id` ASC),   CONSTRAINT `fk_Customer_id_addess`     FOREIGN KEY (`fk_Customer_id_address`)     REFERENCES `mydb`.`Customer` (`Customer_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION,   CONSTRAINT `fk_Manufacturer_id_address`     FOREIGN KEY (`fk_Manufacturer_id_address`)     REFERENCES `mydb`.`Manufacturer` (`Manufacturer_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION,   CONSTRAINT `fk_address_Showroom1   FOREIGN KEY (`Showroom_Showroom_id`)     REFERENCES `mydb`.`Showroom` (`Showroom_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION) ENGINE = InnoDB;   

CREATE TABLE IF NOT EXISTS `mydb`.`phone_number` (   `phone_no` BIGINT(10) NOT NULL,   `Country_code` INT(2) NOT NULL,   `fk_Customer_id_phone` VARCHAR(5) NOT NULL,   CONSTRAINT `Custome_id`     FOREIGN KEY (`fk_Customer_id_phone`)     REFERENCES `mydb`.`Customer` (`Customer_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION) ENGINE = InnoDB; 

CREATE TABLE IF NOT EXISTS `mydb`.`Options` (   `Options_id` VARCHAR(5) NOT NULL,   `Engine` VARCHAR(45) NOT NULL,   `Transmission` VARCHAR(45) NOT NULL,   `color` VARCHAR(15) NOT NULL,   PRIMARY KEY (`Options_id`)) ENGINE = InnoDB;   

CREATE TABLE IF NOT EXISTS `mydb`.`Car_Model` (   `Model_Year` DOUBLE NOT NULL,   `model_id` VARCHAR(5) NOT NULL,   `model_name` VARCHAR(15) NULL,   `availability` VARCHAR(15) NULL,   `Base_price` DOUBLE NULL,   `fk_company_id_model` VARCHAR(5) NOT NULL,   PRIMARY KEY (`model_id`),   INDEX `fk_Car Model_Car_Company1_idx` (`fk_company_id_model` ASC),   CONSTRAINT `fk_Car Model_Car_Company`     FOREIGN KEY (`fk_company_id_model`)     REFERENCES `mydb`.`Car_Company` (`company_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION) ENGINE = InnoDB; 

CREATE TABLE IF NOT EXISTS `mydb`.`CAR` (   `CAR_id` VARCHAR(5) NOT NULL,   `fk_option_id_car` VARCHAR(5) NOT NULL,   `fk_customer_id_car` VARCHAR(5) NOT NULL,   `fk_model_id_car` VARCHAR(5) NOT NULL,   PRIMARY KEY (`CAR_id`),   INDEX `fk_CAR_Options1_idx` (`fk_option_id_car` ASC),   INDEX `fk_CAR_Customer1_idx` (`fk_customer_id_car` ASC),   INDEX `fk_CAR_Car Model1_idx` (`fk_model_id_car` ASC),   CONSTRAINT `fk_Options_id_car`     FOREIGN KEY (`fk_option_id_car`)     REFERENCES `mydb`.`Options` (`Options_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION,   CONSTRAINT `fk_customer_id_car`     FOREIGN KEY (`fk_customer_id_car`)     REFERENCES `mydb`.`Customer` (`Customer_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION,   CONSTRAINT `fk_model_id_car`     FOREIGN KEY (`fk_model_id_car`)     REFERENCES `mydb`.`Car_Model` (`model_id`)  ON DELETE NO ACTION     ON UPDATE NO ACTION) ENGINE = InnoDB;   

CREATE TABLE IF NOT EXISTS `mydb`.`payment` (   `payment_id` VARCHAR(5) NOT NULL,   `fk_Car_id_payment` VARCHAR(5) NOT NULL,   `fk_Showroom_id_payment` VARCHAR(5) NOT NULL,   `fk_Customer_id_payment` VARCHAR(5) NOT NULL,   `amount` REAL NOT NULL,   `Pdate` DATE NOT NULL,   PRIMARY KEY (`payment_id`),   INDEX `CAR_id_idx` (`fk_Car_id_payment` ASC),   INDEX `fk_payment_Showroom1_idx` (`fk_Showroom_id_payment` ASC),   INDEX `fk_payment_Customer1_idx` (`fk_Customer_id_payment` ASC),   CONSTRAINT `fk_patment_car1`     FOREIGN KEY (`fk_Car_id_payment`)     REFERENCES `mydb`.`CAR` (`CAR_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION,   CONSTRAINT `fk_payment_Showroom1`     FOREIGN KEY (`fk_Showroom_id_payment`)     REFERENCES `mydb`.`Showroom` (`Showroom_id`)  ON DELETE NO ACTION     ON UPDATE NO ACTION,   CONSTRAINT `fk_payment_Customer1`     FOREIGN KEY (`fk_Customer_id_payment`)     REFERENCES `mydb`.`Customer` (`Customer_id`)     ON DELETE NO ACTION     ON UPDATE NO ACTION) ENGINE = InnoDB;   


